version: "3.8"

services:

  db:
    image: postgres
    container_name: bot_db
    restart: always
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS
      POSTGRES_DB: $DB_NAME
      PGDATA: "/var/lib/postgresql/data/pgdata"
    networks:
      - botnet
    ports:
      - "5432:5432"
    volumes:
      - /data:/var/lib/postgresql/data/pgdata
    env_file:
      - ".env"

  bot:
    image: "${BOT_IMAGE_NAME}"
    container_name: "${BOT_CONTAINER_NAME}"
    stop_signal: SIGINT
    build:
      context: .
    working_dir: "/usr/src/app/${BOT_NAME}"
    volumes:
    - .:/usr/src/app/${BOT_NAME}
    command: python3 -m bot
    depends_on:
      - db
    restart: always
    networks:
      - botnet
    env_file:
      - ".env"

networks:
  botnet:
    driver: bridge
