version: '3.3'

services:
  bot:
    image: "${BOT_IMAGE_NAME}"
    container_name: "${BOT_CONTAINER_NAME}"
    stop_signal: SIGINT
    build:
      context: .
    restart: always
    env_file:
      - ".env"
    networks:
      - tg_bot

    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

networks:
  tg_bot:
    driver: bridge
